name: project

on: [push]

jobs:
  build:
    name: 统一更新操作
    runs-on: ubuntu-latest
    steps:
      - name: 缓存更新
        run: curl https://purge.jsdelivr.net/gh/KonghaYao/KonghaYaoWeb
      - name: Gitee更新
        run: curl https://gitee.com/api/v5/repos/dongzhongzhidong/visual-test-warehouse/pages/builds
